---
kind: Template
apiVersion: template.openshift.io/v1
metadata:
  annotations:
    description: Cert Manager Deployment to support Acme Certificates
  name: cert-utils-operator-template
labels:
  template: cert-utils-operator-template
objects:
  - kind: OperatorGroup
    apiVersion: operators.coreos.com/v1
    metadata:
      name: cert-utils
    spec:
      targetNamespaces: []
  - kind: Subscription
    apiVersion: operators.coreos.com/v1alpha1
    metadata:
      name: cert-utils-operator
    spec:
      channel: alpha
      installPlanApproval: ${INSTALL_PLAN_APPROVAL}
      name: cert-utils-operator
      source: community-operators
      sourceNamespace: openshift-marketplace
      startingCSV: ${STARTING_CSV}
parameters:
  - name: STARTING_CSV
    value: cert-utils-operator.v1.0.1
  - name: INSTALL_PLAN_APPROVAL
    value: Manual
